// File generated by FlutterFire CLI.
// This file should be replaced with the actual generated file when configuring Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'YOUR-AUTH-DOMAIN',
    storageBucket: 'YOUR-STORAGE-BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBxRwfgmLeSIFJ34w6DLtXRwVujrRP98',
    appId: '1:210466860375:android:8a619464ead7edfc65a212',
    messagingSenderId: '210466860375',
    projectId: 'secure-calling-2025',
    storageBucket: 'secure-calling-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQPADo64jCw28p1lwaS1_nTDZLJkq3C4',
    appId: '1:210466860375:ios:fc1b1fb53bc1a1bb65a212',
    messagingSenderId: '210466860375',
    projectId: 'secure-calling-2025',
    storageBucket: 'secure-calling-2025.firebasestorage.app',
    iosBundleId: 'com.example.securedCalling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQPADo64jCw28p1lwaS1_nTDZLJkq3C4',
    appId: '1:210466860375:ios:fc1b1fb53bc1a1bb65a212',
    messagingSenderId: '210466860375',
    projectId: 'secure-calling-2025',
    storageBucket: 'secure-calling-2025.firebasestorage.app',
    iosBundleId: 'com.example.securedCalling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_AMkY_m4alUO9ZiWIL5e8BBQsiuuGyw4',
    appId: '1:210466860375:web:f75ab0fae7f003c765a212',
    messagingSenderId: '210466860375',
    projectId: 'secure-calling-2025',
    authDomain: 'calling-2025.firebaseapp.com',
    storageBucket: 'secure-calling-2025.firebasestorage.app',
  );

}