// File generated by FlutterFire CLI.
// This file should be replaced with the actual generated file when configuring Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'YOUR-AUTH-DOMAIN',
    storageBucket: 'YOUR-STORAGE-BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeo4wmzIs1X8O1IvGRtutUi4lSKdMz984',
    appId: '1:385594222575:android:55eced1a9c73ff7c68b81a',
    messagingSenderId: '385594222575',
    projectId: 'd-calling-dev',
    storageBucket: 'd-calling-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKcO5Sj0FEcJ6vstPHADUnYkInJUARP1w',
    appId: '1:385594222575:ios:5f5ef3958cc8f1dd68b81a',
    messagingSenderId: '385594222575',
    projectId: 'd-calling-dev',
    storageBucket: 'd-calling-dev.firebasestorage.app',
    iosBundleId: 'com.example.securedCalling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKcO5Sj0FEcJ6vstPHADUnYkInJUARP1w',
    appId: '1:385594222575:ios:5f5ef3958cc8f1dd68b81a',
    messagingSenderId: '385594222575',
    projectId: 'd-calling-dev',
    storageBucket: 'd-calling-dev.firebasestorage.app',
    iosBundleId: 'com.example.securedCalling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4nAY37B-RcljRKVRz8WJ01dDKJZztTw',
    appId: '1:385594222575:web:e0a8945b58d1463168b81a',
    messagingSenderId: '385594222575',
    projectId: 'd-calling-dev',
    authDomain: 'd-calling-dev.firebaseapp.com',
    storageBucket: 'd-calling-dev.firebasestorage.app',
    measurementId: 'G-R6NHLV9LMT',
  );

}